### ISSUE TITLE
Blank page - stored credentials iOs social login

### ISSUE THREAD

**Issue by gregor-srdic** [auth0/auth0-cordova#31]
I am using this lib to add auth0 authentication (google, facebook, database) to Ionic1 application. With plugins, it now works OK on Android, but on iOS, when user has previously logged in with Gmail account, the popup is stuck on blank page, and no tokens are returned to the Ionic app. 
[http://i.imgur.com/lQjUI6n.png](url)
Any idea, what I could be doing wrong?

**Comment by darkyen** [comment]
Can you check if the "Client Type" is selected as "Native" in [Dashboard > Clients](https://manage.auth0.com/#/clients) > Your Client Name > Settings

**Comment by gregor-srdic** [comment]
Thanks. It is not, I am not sure if I can change that on the old client (currently running in production  :( ), will certainly do on the new one. Hopefully it will solve the problem, though I don't really see how that is connected :) The problem only appears on iOs and only when client has been logged in with the same social provider before.

**Comment by hzalaz** [comment]
@gregor-srdic in iOS does it work when the user is not previously logged in?

If not, please check that you installed the plugins detailed in the README correctly. Since cordova plugins tends to be a bit brittle I'd recommend removing the iOS platform and re-adding it.

**Comment by gregor-srdic** [comment]
yes, if I reset the simulator (delete all settings) I can login the first time with google account. Then if I log out, and even if I remove the app and reinstall it, it gets stuck on the blank page :S

**Comment by gregor-srdic** [comment]
after more research I found out that if I sign out of my google account in safari, I can login in cordova app again, first time. 
And further, cordova app sign in always works if i sign into two or more google accounts in safari.
Therefore this must be an issue with automatic login with google account that occurs if user has previously logged in with single google account.

**Comment by gregor-srdic** [comment]
update: we checked the auth0 log and there is a record of a successful login
therefore, this must be a problem when safariViewController tries to automatically redirect back to the app, when credentials are already available.

**Comment by gregor-srdic** [comment]
Does anyone have anything to add to this? It seems painful to ask users to delete safari cookies and web data every time they log out and want to log back in :S

**Comment by MT--** [comment]
`SafariViewController` does not dismiss and callbacks are not running. The logs in the Auth0 dashboard show successful logins and signups.

![img_0018](https://cloud.githubusercontent.com/assets/10172541/26461951/e0624114-414c-11e7-9bca-21a92712fbd8.png)

**Comment by gregor-srdic** [comment]
@MT-- based on the screenshot your problem does not seem the same, I would say you have a problem with callback to the application. Perhaps you should try removing and re-ading the cordova-plugin-customurlscheme plugin and be careful about lower case like [https://github.com/auth0/auth0-cordova/issues/38](#38l)

**Comment by gregor-srdic** [comment]
my situation stops at this
![done](https://cloud.githubusercontent.com/assets/3057225/26484917/0a3ed9e0-41f5-11e7-8a4b-1ca441c8469a.png)

**Comment by gregor-srdic** [comment]
Further research: Also if I revoke access to the application in google/facebook account, I can normally log in once again.

**Comment by gregor-srdic** [comment]
Further research thanks to a colleague revealed, that window.handleOpenURL method was also being invoked when the popup window showed a blank web page.
With some experimenting I was able to find the solution, which is a timeout in handleOpenURL function.
``` 
window.handleOpenURL = function (url) { 
window.setTimeout(function () {
PKCEClient.onRedirectUri(url); 
}, 100);
}
```

**Comment by nitinchangwal** [comment]
In phonegap build the same issue occurred for me.
SafariViewController does not dismiss and callbacks are not running. The logs in the Auth0 dashboard show successful logins and signups.
I tried setTimeout function in window.handleOpenURL but it is not work for me.
i tried deeplink plugin instead of colors chema url also.

**Comment by anacesponda** [comment]
Hi @gregor-srdic I'm having the same problem that you were having. Fb is working fine but when trying to sign in with Gmail, the first time it's 👌 , but once the user is logged it shows me the Website Name. I tried with your solution but still not working. Do you have any news about it?
Thanks

**Comment by GODBS** [comment]
I have the exact same issue :(

**Comment by jwmann** [comment]
I was able to solve this for iOS by 'Erasing all Settings and Contents' from the Simulator and running the emulator again from scratch.

Must be some kind of cache that somehow persists even after you quit the simulator?
