### ISSUE TITLE
Login not working on specific devices

### ISSUE THREAD

**Issue by dtaalbers** [auth0/auth0-cordova#54]
I've built an Ionic 2 app that I am about to release to the Google Play Store and the App Store. Sadly I am getting reports that some users cannot log in on specific devices. Most devices do work allow logging in but some do not. It is hard to test all devices, but luckily a customer was able to lend me a device where he could not log in.

This device is a Galaxy tab and indeed the app does not allow me to log in on that device. I've tried to log in with the same app on a few of my own android/ios devices that I have lying around and on those we can log in. The login screen appears just fine on the Galaxy Tab but when I enter my credentials and press login I get an `ERR_UNKNOWN_URL_SCHEME` error on my callback URL. So I dove in the Auth0-Cordova plugin to see what is happening and the only difference I saw between the two devices (that work and do not work) is that the login screen gets opened a different way.

It is this piece of code that is located in `@auth0/cordova/docs/src/agent/index.js` of the `@auth0/cordova` npm package that is producing different results on the devices. Again we are still talking about the app I build.

```
module.exports = function getAgent(callback) {
    console.log(BrowserAgent, 'browser agent');
    return BrowserAgent.isAvailable(function (available) {
        console.log(available, 'browser agent available');
        if (available) {
            // Variable 'available' is true on the device that works
            return callback(null, new BrowserAgent());
        }
        // Variable 'available' is false on the device that does not work
        return callback(null, new WebViewAgent());
    });
};
```

When I use the chrome inspect feature to check to see what is going on, I see on the device that works normally that it has one view open (the login screen). But when I check the device that does not work it has two view open, the login screen has a view and the app opens in a different view. It looks to me that whenever I log in on the device that doesn't work it can not redirect back to the app after validating the credentials because they are opened in different views/screens/browser. Perhaps the issue? I don't know.

So I decided to try to reproduce it in a standalone app. I've downloaded your auth0/ionic2 example here, https://auth0.com/docs/quickstart/native/ionic2/01-login, installed the node_modules and configured the auth0 settings.

First I deployed the login example app on the device that worked with my app, the LG Android device (see specs below). I could log in on the LG without any problems. Next, I deployed the same app on the Samsung Galaxy Tab (the device that didn't allow me to log in) and on this device the login failed. Not exactly the same issue as in my own app, but it the same code base causes an issue.

I check the used `agent` on each device by logging it in `@auth0/src/index.js`. 

```
  getAgent(function (err, agent) {
        console.log(agent, 'USED AGENT');
        if (err) {
            return callback(err);
        }
```

As you can see in the screenshots, you can see the working device uses the Browser as agent and the device that does not work is (trying) to use the Webview. As you can see the example app also produces the error.

```
cannot read property 'open' of undefined.
```

And from there I don't know what to do anymore. I would appreciate some help with the issue.

Devices used 

* Galaxy Tab A (2016) SM-T280 (doesn't work) Android version 5.1.1 
* LG -D722 (works) Android version 5.0.2 
* iPhone 5s (works) iOS version 11.0.3

The sample project that has been used can be found [here](https://www.dropbox.com/s/lpeqtgmdhh942uh/01-login.zip?dl=0). Note that I have removed my own auth0 configuration in the `AuthService`.

Related:
* https://community.auth0.com/questions/5235/blank-page-authentication-auth0-linkedin-ionic-2

![samsunggalaxytab](https://user-images.githubusercontent.com/6512556/31933961-f09c0792-b8aa-11e7-8832-7c14c3a00073.png)

![lg](https://user-images.githubusercontent.com/6512556/31933978-023c1da2-b8ab-11e7-91df-af25f76bde59.png)

**Comment by brassier** [comment]
I actually ran into this issue yesterday.  For me, the problem was solved by making sure the Android device had the chrome browser installed and enabled.  It didn't have to be the default browser, but it has to be available.

Hope it helps.

**Comment by dtaalbers** [comment]
Thanks @brassier 

I did that (updating chrome browser) on the device I have (that doesn't work) and I could finally log in. I asked one of my other customers to test the chrome update as well. He uses a different device (ACER tablet) with same android version but he already had its chrome browser up-to-date. Redirecting after logging in still does not work on his device. Sadly I can't expect all of my customers or feature customers to update their browser. Is there a different solution for this issue that I can try?

```
module.exports = function getAgent(callback) {
    return BrowserAgent.isAvailable(function (available) {
        if (available) {
            // Here the app is using the SafariWebViewController.
            // when this is used the login & redirect works
            return callback(null, new BrowserAgent());
        }
        // When the SafariWebViewController is not available it falls back on the
        // Cordova InAppBrowser plugin which does not allow the redirection after logging in 
        return callback(null, new WebViewAgent());
    });
};
```
As you can see in my comments it falls back to the `InAppBrowser` on those specific devices. And when using the `InAppBrowser` redirecting after logging in fails. It it suppose to work normally when you work with `InAppBrowser`?

**Comment by darkyen** [comment]
The BrowserAgent relies on SafariViewController Cordova Plugin, you'll need to ensure that your app is packaged with support for custom tabs explicitely for this to work https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/wiki#to-use-with-chrome-custom-tabs-for-android

**Comment by brassier** [comment]
I have also had reports of 2 (out of ~400) Android users unable to log in.  In their case they successfully log into Auth0, and it brings them back to the login page of the app (as opposed to the authenticated home page).  They don't get an obvious error (e.g. `ERR_UNKNOWN_URL_SCHEME`), but that may be happening behind the scenes.  I haven't been lucky enough to have a device that can recreate this.

So I agree that there seems to be some set of conditions where this cordova package won't allow logins in Android.  Having Chrome enabled/updated may help some of these cases (but likely not all).

**Comment by webbkvalite** [comment]
This problem reemerges in Cordova Android 7.
Immediately when trying to login the following is thrown:
 {"stack":"TypeError: Cannot call method 'isAvailable' of undefined\n at
            Function.Browser.isAvailable (http://192.168.2.226:8100/build/vendor.js:222233:31)\n at getAgent
            (http://192.168.2.226:8100/build/vendor.js:222212:23)\n at CordovaAuth.authorize
            (http://192.168.2.226:8100/build/vendor.js:138888:3)\n at AuthServiceNative.login
            (http://192.168.2.226:8100/build/main.js:6438:16)\n at SearchPage.login
            (http://192.168.2.226:8100/build/main.js:6748:19)\n at Object.eval [as handleEvent]
            (ng:///AppModule/SearchPage.ngfactory.js:37:23)\n at handleEvent
            (http://192.168.2.226:8100/build/vendor.js:12356:138)\n at callWithDebugContext
            (http://192.168.2.226:8100/build/vendor.js:13825:42)\n at Object.debugHandleEvent [as handleEvent]
            (http://192.168.2.226:8100/build/vendor.js:13413:12)\n at dispatchEvent
            (http://192.168.2.226:8100/build/vendor.js:8972:21)","message":"Cannot call method 'isAvailable' of
            undefined","ngDebugContext":{}}

**Comment by arichbell** [comment]
We've run into an issue that sounds similar to this.  We are working on reproducing the issue to get an error log, but.. Has anyone on this thread come up with any other solutions?

**Comment by Widcket** [comment]
Closing this one. Please ping if this is still an issue.
